/**
 * Remote rare-sticker list — fetch + cache layer.
 *
 * The bundled `public/rare_stickers.json` is the fallback baked into the
 * extension. The *live* list is published publicly at the raw GitHub URL
 * below and regenerated by a private, local Python tool (kept off-repo). The
 * service worker refreshes the list at most once per TTL window — or on demand
 * via the popup's "Atualizar raros" button — and caches it in
 * `chrome.storage.local`. `rare-data.ts` prefers this cache and falls back to
 * the bundled file when it's absent/stale/unreadable, so a network failure can
 * never leave the scanner without a DB.
 *
 * Same-file design: the URL points at the very file the build bundles, so the
 * Python tool just regenerates `public/rare_stickers.json`, commits, and pushes
 * — no separate data repo, no auth token (the repo is public). host_permission
 * is scoped to `raw.githubusercontent.com/Jhonysganzerla/*`, never `<all_urls>`.
 */

export const REMOTE_RARE_URL =
  'https://raw.githubusercontent.com/Jhonysganzerla/skinsight/main/public/rare_stickers.json';

/** Auto-refresh window — the SW won't hit the network more often than this. */
export const REMOTE_RARE_TTL_MS = 24 * 60 * 60 * 1000;

const KEY_RARE_REMOTE = 'rare_remote';

export type RareEntry = [string, number];

export interface RareRemoteCache {
  /** Parsed [name, price] pairs exactly as published. */
  data: RareEntry[];
  /** When we last successfully fetched (epoch ms). */
  fetchedAt: number;
}

/** Validate parsed JSON is the expected `Array<[string, number]>`. */
export function isValidRareList(x: unknown): x is RareEntry[] {
  if (!Array.isArray(x) || x.length === 0) return false;
  for (const row of x) {
    if (!Array.isArray(row) || row.length < 2) return false;
    if (typeof row[0] !== 'string' || typeof row[1] !== 'number') return false;
  }
  return true;
}

export async function getRareRemoteCache(): Promise<RareRemoteCache | null> {
  const r = (await chrome.storage.local.get(KEY_RARE_REMOTE)) as Record<string, unknown>;
  const c = r[KEY_RARE_REMOTE] as Partial<RareRemoteCache> | undefined;
  if (!c || typeof c.fetchedAt !== 'number' || !isValidRareList(c.data)) return null;
  return { data: c.data, fetchedAt: c.fetchedAt };
}

async function setRareRemoteCache(cache: RareRemoteCache): Promise<void> {
  await chrome.storage.local.set({ [KEY_RARE_REMOTE]: cache });
}

export interface RefreshResult {
  ok: boolean;
  count?: number;
  fetchedAt?: number;
  error?: string;
  /** True when we skipped the network because the cache was still fresh. */
  cached?: boolean;
}

/**
 * Fetch the remote list and cache it. `force` bypasses the TTL freshness check
 * (the popup button passes force=true; scan-start and SW boot pass false).
 * Never throws — callers read `ok`/`error`.
 */
export async function refreshRareRemote(force = false): Promise<RefreshResult> {
  if (!force) {
    const existing = await getRareRemoteCache();
    if (existing && Date.now() - existing.fetchedAt < REMOTE_RARE_TTL_MS) {
      return {
        ok: true,
        count: existing.data.length,
        fetchedAt: existing.fetchedAt,
        cached: true,
      };
    }
  }
  try {
    const res = await fetch(REMOTE_RARE_URL, { cache: 'no-store' });
    if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
    const json: unknown = await res.json();
    if (!isValidRareList(json)) return { ok: false, error: 'malformed list' };
    const cache: RareRemoteCache = { data: json, fetchedAt: Date.now() };
    await setRareRemoteCache(cache);
    return { ok: true, count: json.length, fetchedAt: cache.fetchedAt };
  } catch (e) {
    return { ok: false, error: String((e as Error)?.message ?? e) };
  }
}
